--집합 
-- 사원의 사번, 직무번호를 출력하시오 (현재 사원의 직무알림 
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES;  -- 현재 이 사원의 직무 
-- 직무경력(JOBHISTORY)의 사번, 직무번호를 출력하시오. 
SELECT EMPLOYEE_ID, JOB_ID, START_DATE, END_DATE
FROM JOB_HISTORY;

--101번 사원의 이전직무와 현재직무를 모두 출력하시오 
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY 
WHERE EMPLOYEE_ID=101
UNION
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID=101; --101 사원의 정보만 보기 
-- 행을 합치는 작업이 UNION이다. 

-- SELECT절에서 사용한 컬럼의 갯수가 일치해야 하고 각 컬럼의 자료형이 일치해야 한다. 
-- 숫자, 문자, 숫자, 문자형으로 일치해야 한다. 
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY 
UNION
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES;-- EMPLOYEES자료와 JOB_HISTORY자료가 합쳐진것을 볼 수 있다. 


SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY 
WHERE EMPLOYEE_ID=176
UNION
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID=176;

SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY 
WHERE EMPLOYEE_ID=176
UNION ALL
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID=176;



SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY 
UNION
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
ORDER BY EMPLOYEE_ID DESC;
-- 교집합 : INTERSECT 
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY 
INTERSECT
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES;

-- 차집합 
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY 
MINUS
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES;
-- 교집합에 있었던 것이 
-- 차집합에서 어떤 것을 먼저 하느냐에 따라 결과가 달라지게 된다. 
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
MINUS
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY ;

