CREATE OR REPLACE VIEW ORDER_VIEW 
AS select INFO.ORDER_NO,INFO.ORDER_ID, INFO.ORDER_DT, LINE.ORDER_PROD_NO, P.PROD_NAME, P.PROD_PRICE, LINE.ORDER_QUANTITY 
FROM ORDER_INFO INFO JOIN ORDER_LINE LINE ON (INFO.ORDER_NO = LINE.ORDER_NO) 
JOIN PRODUCT P ON (LINE.ORDER_PROD_NO = P.PROD_NO)
WHERE ORDER_ID = 'id2'
ORDER BY ORDER_NO DESC, PROD_NAME ASC; 

----
--USER_VIEWS에 뷰정보가 저장된다. 
SELECT *FROM USER_TABLES;
SELECT * FROM USER_VIEWS;

--'id2'고객의 주문번호, 주문일자, 주문상품번호, 주문상품명, 
SELECT * 
FROM ORDER_VIEW 
WHERE ORDER_ID = 'id2';




CREATE SEQUENCE ORDER_SEQ;
DROP SEQUENCE ORDER_SEQ; -- 삭제 
CREATE SEQUENCE ORDER_SEQ 
START WITH 4 
INCREMENT BY 2 
MAXVALUE 10;   --4부터 시작해서 

SELECT ORDER_SEQ.NEXTVAL FROM DUAL; --4
SELECT ORDER_SEQ.NEXTVAL FROM DUAL; --6
SELECT ORDER_SEQ.NEXTVAL FROM DUAL; --8
SELECT ORDER_SEQ.NEXTVAL FROM DUAL; --10
SELECT ORDER_SEQ.NEXTVAL FROM DUAL; -- MAXVAL 넘어 서서 에러가 남 
-- 최소값으로 순환시키려면 CYCLE설정 필요함 

CREATE SEQUENCE ORDER_SEQ 
START WITH 4 
INCREMENT BY 2 
MAXVALUE 10;   --4부터 시작해서
NO; -- CYCLE설정하고 싶지 않을 때 -- 기본값이 

CREATE SEQUENCE ORDER_SEQ 
START WITH 4 
INCREMENT BY 2 
MAXVALUE 10   --4부터 시작해서
CYCLE 
CACHE 3;  -- 미리 여러개 안 만들어놓아도 된다. 
-- 사이클 설정하려면 기본 CASH가 있어야 한다. 
-- 미리 일련번호를 여러개 만들어두는 데 그것을 CHSH라고 하고 기본값은 20개이다. 
-- 20개 조건에 위배된다는 것이다. 


SELECT ORDER_SEQ.NEXTVAL FROM DUAL; --4
SELECT ORDER_SEQ.NEXTVAL FROM DUAL; --6
SELECT ORDER_SEQ.NEXTVAL FROM DUAL; --8
SELECT ORDER_SEQ.NEXTVAL FROM DUAL; --10
SELECT ORDER_SEQ.NEXTVAL FROM DUAL; -- 1
SELECT ORDER_SEQ.CURRVAL FROM DUAL; --현재 값 보기 


CREATE SEQUENCE ORDER_SEQ 
START WITH 4 
INCREMENT BY 2 
MAXVALUE 10   --4부터 시작해서
CYCLE 
CACHE 3;  --
INSERT INTO ORDER_INFO(ORDER_NO, ORDER_ID, ORDER_DT) VALUES (ORDER_SEQ.NEXTVAL, 'id2', SYSDATE); 
INSERT INTO ORDER_LINE(ORDER_NO, ORDER_PROD_NO, ORDER_QUANTITY) VALUES (ORDER_SEQ.CURRVAL, 'C0001', 1);

SELECT * FROM ORDER_VIEW;

DROP SEQUENCE ORDER_SEQ;
CREATE SEQUENCE ORDER_SEQ
START WITH 5;