--1. 부서평균급여가 9500 이상인 부서대상으로 부서별 최대급여, 평균급여, 인원수를
--출력하시오.
--평균급여를 소숫점둘째자리에서 반올림한다
--단, 각부서의 최대급여와 최소급여가 같은 부서는 제외한다.

-- 부서별은 부서이름도 괜찮고 부서ID도 가능하다. 
SELECT DEPARTMENT_NAME, MAX(SALARY), ROUND(AVG(SALARY),1), COUNT(*) 
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING AVG(SALARY)>= 9500 AND MAX(SALARY) <> MIN(SALARY);



--2. region_name 이 "Americas"인 지역의 사원급여 중 최소급여값을 출력하시오
SELECT MIN(SALARY) 최소급여 
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
                JOIN COUNTRIES C ON L.COUNTRY_ID= C.COUNTRY_ID
                JOIN REGIONS R ON C.RIGION_ID = R.REGION_ID
WHERE REGION_NAME = 'Americas';


SELECT MIN(SALARY) 최소급여
FROM EMPLOYEES
WHERE REGION_ID IN(
(SELECT DEPARTMENT_id
from 

(SELECT COUNTY_ID
    FROM COUNTRIES
    WHERE REGION_ID 
IN

(SELECT REGION_ID
FROM REGIONS 
WHERE REGION_NAME = 'Americas'));
--3. job_title 이 'Programmer'인 매니저로 부터 관리받는 사원중 부서명이'IT'인
--부서의 사번, 이름을 출력하시오.
-- 매니저의 JOB TITLE

SELECT E.EMPLOYEE_ID, E.FIRST_NAME
FROM EMPLOYEES E JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
                JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                JOIN JOBS J ON M.JOB_ID = J.JOB_ID
WHERE (J.JOB_TITLE = 'Programmer') AND (D.DEPARTMENT_NAME = 'IT');

SELECT JOB_ID FROM JOBS WHERE JOB_TITLE = 'Programmer';

--4. job_title 이 Manager 로 끝나는 사원들의 job_title 별 평균 급여을 출력하시오.
SELECT JOB_TITLE, AVG(SALARY)
FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE JOB_TITLE LIKE '%Manager'
GROUP BY JOB_TITLE;
--5. 'Seattle', 'Toronto'도시에 근무하는 사원들의 도시명,사번, 이름, 부서 ID, 
--부서명 을 출력하시오(ScalarQuery 로 완성
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID),
(SELECT CITY FROM LOCATIONS  WHERE LOCATION_ID= (SELECT LOCATION_ID
FROM DEPARTMENS D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID)
FROM EMPLOYEES E 
WHERE DEPARTMENT_ID IN(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE LOCATION_ID IN
(SELECT LOCATION_ID FROM LOCATIONS WHERE CITY IN('Seattle', 'Toronto')
)
);  