CREATE TABLE POINT (
    POINT_ID VARCHAR2(10) PRIMARY KEY, 
    POINT_SCORE NUMBER(3)
);
/
SELECT * FROM POINT;

--고객이 추가되면 포인트도 자동추가된다. 
CREATE OR REPLACE TRIGGER TRIG1
AFTER INSERT ON CUSTOMER 
FOR EACH ROW 
BEGIN 
    INSERT INTO POINT(POINT_ID, POINT_SCORE) 
    VALUES (:NEW.id ,0);
END; 
/
--
-- 고객추가 
INSERT INTO CUSTOMER(ID, PWD) VALUES ('TEST', 'P');
/
SELECT * FROM CUSTOMER; 
-- 포인트 자동 추가되었는지 확인 
SELECT * FROM POINT;
/
--
-- 주문기본정보추가되면 포인트는 1점 증가한다. 
CREATE OR REPLACE TRIGGER TRIG2
-- TODO 
AFTER INSERT ON ORDER_INFO
FOR EACH ROW
BEGIN 
    UPDATE POINT SET POINT_SCORE = POINT_SCORE+1 WHERE POINT_ID=:NEW.ORDER_ID;
   
END;
/
------
-- 주문추가 
INSERT INTO ORDER_INFO(ORDER_NO, ORDER_ID, ORDER_DT) VALUES (ORDER_SEQ.NEXTVAL, 'TEST', SYSDATE);
-- 주문확인 
SELECT * FROM ORDER_INFO;
-- 포인트점수 확인 
SELECT * FROM POINT;

drop trigger trig1;
drop trigger trig2; 
